# Generated by Django 4.2 on 2023-05-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_finder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchedleagues",
            name="radius",
            field=models.IntegerField(default=25),
        ),
    ]
