# Generated by Django 4.2 on 2023-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_finder", "0002_searchedleagues_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchedleagues",
            name="age_searched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchedleagues",
            name="sport_level",
            field=models.CharField(default="", max_length=255),
        ),
    ]
