# Generated by Django 4.2 on 2023-07-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="form_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitter", models.CharField(max_length=100)),
                ("submitter_email", models.EmailField(max_length=254)),
                ("submitter_phone", models.CharField(max_length=17, null=True)),
                ("submitter_message", models.TextField(max_length=500, null=True)),
                ("followed_up", models.BooleanField(default=False)),
                (
                    "form_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forms_api.form_type",
                    ),
                ),
            ],
        ),
    ]
