# Generated by Django 4.2 on 2023-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_api", "0002_alter_form_submitter_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="submitter_phone",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
