# Generated by Django 4.2 on 2023-07-24 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_api", "0003_alter_form_submitter_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="submit_date_tm",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 24, 16, 34, 53, 603340, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
