# Generated by Django 4.2 on 2023-07-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scraped_product",
            old_name="product_type",
            new_name="product_type_reltn",
        ),
    ]
